# Originally copied from: https://github.com/kubernetes/kubernetes/tree/master/cluster/saltbase/salt/fluentd-gcp
# Also see the post: http://blog.kubernetes.io/2015/06/cluster-level-logging-with-kubernetes.html

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      dnsPolicy: Default
      containers:
      - name: fluentd
        image: 192.168.99.100:5000/fluentd:latest
        resources:
          limits:
            memory: 200Mi
          requests:
        # Any change here should be accompanied by a proportional change in CPU
        # requests of other per-node add-ons (e.g. kube-proxy).
            cpu: 80m
            memory: 200Mi
        env:
        - name: FLUENTD_ARGS
          value: -v
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlogcontainers
          mountPath: /var/log/containers
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: mntsda1
          mountPath: /mnt/sda1
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlogcontainers
        hostPath:
          path: /var/log/containers
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: mntsda1
        hostPath:
          path: /mnt/sda1
